// ─────────────────────────────────────────────────────────────
// Word list — 400+ Portuguese words for the Krypton board
// ─────────────────────────────────────────────────────────────

/** Full pool of Portuguese words available for the game board. */
export const WORD_POOL: readonly string[] = [
  // Natureza
  'FLORESTA',
  'MONTANHA',
  'OCEANO',
  'DESERTO',
  'VULCÃO',
  'GLACIAR',
  'LAGOA',
  'PÂNTANO',
  'SAVANA',
  'TUNDRA',
  'CÂNION',
  'CACHOEIRA',
  'ILHA',
  'ESTREITO',
  'BAÍA',
  'CHAPADA',
  'PLANALTO',
  'VALE',
  'GRUTA',
  'ARRECIFE',
  'MANGUE',
  'TAIGA',
  'ESTEPE',
  'ARQUIPÉLAGO',

  // Animais
  'JAGUAR',
  'FALCÃO',
  'TUBARÃO',
  'BALEIA',
  'GOLFINHO',
  'LULA',
  'PANTERA',
  'LOBO',
  'RAPOSA',
  'CORUJA',
  'COBRA',
  'LAGARTO',
  'TARTARUGA',
  'PINGUIM',
  'ALCE',
  'BISÃO',
  'RINOCERONTE',
  'GIRAFA',
  'ELEFANTE',
  'CHITA',
  'LEÃO',
  'TIGRE',
  'URSO',
  'GORILA',
  'CAPIVARA',
  'TATU',
  'ONÇA',
  'ANTA',
  'TAMANDUÁ',
  'ARARA',
  'TUCANO',
  'COELHO',
  'LOBO',
  'CEGONHA',
  'FLAMINGO',
  'CONDOR',

  // Objetos
  'ESPELHO',
  'BÚSSOLA',
  'LANTERNA',
  'ÂNCORA',
  'RELÓGIO',
  'TELESCÓPIO',
  'MICROSCÓPIO',
  'BALANÇA',
  'CHAVE',
  'CADEADO',
  'COFRE',
  'BAÚ',
  'CANIVETE',
  'BINÓCULO',
  'MAPA',
  'BÚSSOLA',
  'GLOBO',
  'PERGAMINHO',
  'PERGAMINHO',
  'ESTATUETA',
  'CRISTAL',
  'MOEDA',
  'MEDALHA',
  'TROFÉU',
  'ANEL',
  'COROA',
  'CETRO',
  'ESCUDO',
  'LANÇA',
  'MACHADO',
  'ARCO',
  'FLECHA',
  'ESPADA',
  'ARMADURA',
  'CAPACETE',
  'CAPA',

  // Lugares
  'CASTELO',
  'PALÁCIO',
  'TORRE',
  'FORTALEZA',
  'CATEDRAL',
  'TEMPLO',
  'PIRÂMIDE',
  'COLISEU',
  'FAROL',
  'PORTO',
  'MERCADO',
  'MUSEU',
  'BIBLIOTECA',
  'LABORATÓRIO',
  'ARENA',
  'ESTÁDIO',
  'CIRCO',
  'TEATRO',
  'CINEMA',
  'GALERIA',
  'AQUÁRIO',
  'ZOOLÓGICO',
  'JARDIM',
  'PARQUE',
  'CAVERNA',
  'LABIRINTO',
  'MANSÃO',
  'CABANA',
  'TRAPICHE',
  'DOCA',

  // Ciência e Tecnologia
  'ÁTOMO',
  'NEUTRON',
  'FÓTON',
  'QUASAR',
  'NEBULOSA',
  'GALÁXIA',
  'BURACO NEGRO',
  'PULSAR',
  'COMETA',
  'ASTERÓIDE',
  'SATÉLITE',
  'ÓRBITA',
  'GRAVIDADE',
  'MAGNETISMO',
  'RADIAÇÃO',
  'ESPECTRO',
  'LASER',
  'PLASMA',
  'VÍRUS',
  'BACTÉRIA',
  'GENE',
  'DNA',
  'PROTEÍNA',
  'ENZIMA',
  'ROBÔ',
  'ANDROIDE',
  'CHIP',
  'CIRCUITO',
  'PROCESSADOR',
  'SERVIDOR',
  'ALGORITMO',
  'CÓDIGO',
  'REDE',
  'PORTAL',
  'SINAL',
  'FREQUÊNCIA',

  // Profissões e Personagens
  'AGENTE',
  'DETETIVE',
  'ESPIÃO',
  'PIRATA',
  'NINJA',
  'SAMURAI',
  'CAVALEIRO',
  'ARQUEIRO',
  'MAGO',
  'ALQUIMISTA',
  'INVENTOR',
  'CIENTISTA',
  'EXPLORADOR',
  'NAVEGADOR',
  'PILOTO',
  'ASTRONAUTA',
  'MERGULHADOR',
  'ESCALADOR',
  'CAÇADOR',
  'RASTREADOR',
  'ARQUEÓLOGO',
  'GEÓLOGO',
  'BIÓLOGO',
  'FÍSICO',

  // Conceitos abstratos
  'SOMBRA',
  'ECO',
  'MIRAGEM',
  'ILUSÃO',
  'ENIGMA',
  'MISTÉRIO',
  'SEGREDO',
  'CÓDIGO',
  'CIFRA',
  'PISTA',
  'RASTRO',
  'INDÍCIO',
  'TEORIA',
  'HIPÓTESE',
  'PARADOXO',
  'DILEMA',
  'CONFLITO',
  'ALIANÇA',
  'TRAIÇÃO',
  'LEALDADE',
  'HONRA',
  'GLÓRIA',
  'VITÓRIA',
  'DERROTA',
  'DESTINO',
  'ACASO',
  'SORTE',
  'RISCO',
  'PERIGO',
  'AMEAÇA',
  'PODER',
  'FORÇA',
  'ENERGIA',
  'CAOS',
  'ORDEM',
  'EQUILÍBRIO',

  // Elementos e Forças
  'FOGO',
  'ÁGUA',
  'TERRA',
  'VENTO',
  'TROVÃO',
  'RELÂMPAGO',
  'GEADA',
  'NEBLINA',
  'FUMAÇA',
  'VAPOR',
  'GELO',
  'LAVA',
  'TEMPESTADE',
  'FURACÃO',
  'TORNADO',
  'TSUNAMI',
  'TERREMOTO',
  'ECLIPSE',
  'MARÉ',
  'CORRENTE',
  'AVALANCHE',
  'ERUPÇÃO',
  'CRATERA',
  'FISSURA',

  // Espaço
  'COSMOS',
  'UNIVERSO',
  'DIMENSÃO',
  'PORTAL',
  'FENDA',
  'VÓRTEX',
  'CONSTELAÇÃO',
  'ASTERISMO',
  'ECLIPSE',
  'SOLSTÍCIO',
  'EQUINÓCIO',
  'HORIZONTE',
  'ZENITE',
  'NADIR',
  'MERIDIANO',
  'PARALELO',
  'LONGITUDE',
  'LATITUDE',

  // Mitologia e Fantasia
  'DRAGÃO',
  'FÊNIX',
  'GRIFO',
  'QUIMERA',
  'KRAKEN',
  'LEVIATÃ',
  'MINOTAURO',
  'CICLOPE',
  'ESFINGE',
  'MEDUSA',
  'SIRENE',
  'CENTAURO',
  'GOLEM',
  'FANTASMA',
  'VAMPIRO',
  'LOBISOMEM',
  'ELFO',
  'ANÃO',
  'ORÁCULO',
  'PROFECIA',
  'LENDA',
  'MITO',
  'RELÍQUIA',
  'ARTEFATO',

  // Cores e Materiais
  'ÉBANO',
  'MARFIM',
  'ÂMBAR',
  'SAFIRA',
  'RUBI',
  'ESMERALDA',
  'QUARTZO',
  'GRANITO',
  'MÁRMORE',
  'OBSIDIANA',
  'BRONZE',
  'PLATINA',
  'TITÂNIO',
  'CROMO',
  'COBALTO',
  'ÍNDIGO',
  'CARMIM',
  'ESCARLATE',

  // Verbos substantivados / Ações
  'FUGA',
  'CAÇA',
  'BUSCA',
  'MISSÃO',
  'RESGATE',
  'INVASÃO',
  'DEFESA',
  'ATAQUE',
  'BLOQUEIO',
  'CERCO',
  'EMBOSCADA',
  'RECUO',
  'SALTO',
  'MERGULHO',
  'ESCALADA',
  'TRAVESSIA',
  'INFILTRAÇÃO',
  'INTERCEPÇÃO',

  // Tecnologia futurista
  'HOLOGRAMA',
  'CIBERNÉTICO',
  'EXOESQUELETO',
  'NANOBÔ',
  'MATRIZ',
  'NEXO',
  'PROTOCOLO',
  'INTERFACE',
  'TERMINAL',
  'NÚCLEO',
  'REATOR',
  'GERADOR',
  'AMPLIFICADOR',
  'SENSOR',
  'SCANNER',
  'DETECTOR',
  'RASTREADOR',
  'EMISSOR',

  // Instrumentos e Arte
  'VIOLINO',
  'TAMBOR',
  'TROMPETE',
  'HARPA',
  'FLAUTA',
  'ÓRGÃO',
  'PINCEL',
  'PALETA',
  'TELA',
  'ESCULTURA',
  'MOSAICO',
  'GRAVURA',
  'MURAL',
  'VITRAL',
  'FRESCO',
  'ÍCONE',
  'RELEVO',
  'BUSTO',

  // Comida e Natureza viva
  'COGUMELO',
  'SAMAMBAIA',
  'LÍQUEN',
  'MUSGO',
  'BAMBU',
  'CACTO',
  'MAGNÓLIA',
  'ORQUÍDEA',
  'BROMÉLIA',
  'CIPÓ',
  'RAIZ',
  'SEMENTE',
  'ESPORO',
  'PÓLEN',
  'NÉCTAR',
  'RESINA',
  'SEIVA',
  'CASCA',

  // Navegação e Viagem
  'BÚSSOLA',
  'SEXTANTE',
  'ASTROLÁBIO',
  'CATALEJO',
  'TIMÃO',
  'QUILHA',
  'MASTRO',
  'VELA',
  'HÉLICE',
  'TURBINA',
  'MOTOR',
  'COMBUSTÍVEL',
  'ROTA',
  'TRILHA',
  'ATALHO',
  'DESVIO',
  'CAMINHO',
  'PASSAGEM',
  // Extras
  'NÉVOA',
  'ABISMO',
  'CLAREIRA',
  'AURORA',
] as const;

if (WORD_POOL.length < 400) {
  // Compile-time check — will error if the pool shrinks below threshold.
  // (TypeScript `satisfies` cannot check length at compile time for large arrays,
  //  so we use a runtime assertion in development.)
  console.warn(
    `[krypton/engine] Word pool has only ${WORD_POOL.length} words. Recommended: ≥ 400.`,
  );
}

/**
 * Picks `n` unique random words from the word pool.
 * Uses a Fisher-Yates partial shuffle so it's O(n).
 *
 * @throws {RangeError} if `n` is larger than the pool size.
 */
export function pickWords(n: number): string[] {
  if (n > WORD_POOL.length) {
    throw new RangeError(`Cannot pick ${n} words from a pool of ${WORD_POOL.length}.`);
  }

  // Work on a mutable copy — Fisher-Yates partial shuffle
  const pool = [...WORD_POOL] as string[];
  for (let i = 0; i < n; i++) {
    const j = i + Math.floor(Math.random() * (pool.length - i));
    // swap pool[i] and pool[j]
    const tmp = pool[i]!;
    pool[i] = pool[j]!;
    pool[j] = tmp;
  }

  return pool.slice(0, n);
}
